### ISSUE TITLE
OSC Event Receiver fails to receive messages from TouchOSC via tethering

### ISSUE THREAD

**Issue by ColinPeyrat** [keijiro/OscJack#18]
Hi !

First, thanks you for this package, it's awesome !
When I'm using it connected to my smartphone Wi-Fi thetering OscJack is not receiving anything...

It's working on if both devices are connected on my home Wi-Fi

There is a screenshot of TouchOSC configuration screen :
![Screenshot_20190613-193958](https://user-images.githubusercontent.com/13947885/59455171-ec361180-8e13-11e9-89cf-b81337457eae.jpg)

**Comment by keijiro** [comment]
I guess that there is an issue in your network configuration. Please use other OSC monitoring apps like [OSCTestApp](https://vdmx.vidvox.net/blog/freebies) or [OSC Data Monitor](https://www.kasperkamperman.com/blog/processing-code/osc-datamonitor/) to check if it's correctly connected.

**Comment by ColinPeyrat** [comment]
I've tried [OSCTestApp](https://www.kasperkamperman.com/blog/processing-code/osc-datamonitor/) and it's working:

![javaw_oEP1epY37H](https://user-images.githubusercontent.com/13947885/59516233-2c9f9900-8ec1-11e9-9bd3-7d00461d5e60.png)

And still nothing in OSC Monitor in Unity, I use the same TouchOSC configuration and this settings in Unity:

![Unity_lE7fL5eORY](https://user-images.githubusercontent.com/13947885/59516267-4a6cfe00-8ec1-11e9-8604-c7dd720c071f.png)

**Comment by keijiro** [comment]
How about building the project? Build the project, close Unity Editor, then run it. I'd like to know if it's an Editor problem or not.

**Comment by ColinPeyrat** [comment]
I've tried to run a build while editor was closed and that still don't work. Also, OSC Data monitor was still working.

**Comment by mozis84** [comment]
Hi, I have the same issue! Everything seem's fine when I use it with OSC Data monitor, but it doesn't work on Unity. I also tried another Unity package, similar to OSC Jack and I still have no signal. If anyone has a clue Please let me know :-(

**Comment by keijiro** [comment]
I was also struggling with this issue, but I found that it starts receiving messages after one or two minutes elapsed. I'm not sure why, but it seems to need some amount of wait before sending/receiving UDP data. So, could you re-test it for several minutes?

**Comment by mozis84** [comment]
Thanx for your response! I figured out what was the problem. In my case, it was a stupid mistake. I just needed to turn off the firewall!
Btw... a big thanx for sharing all your great projects, I have a lot of respect for what you do!

**Comment by keijiro** [comment]
Thanks for the clarification.

Now I'm closing this issue. Please feel free to reopen if it reproduces under some environment.

**Comment by BastienGermain** [comment]
Hi I think I encounter the same issue. I am trying to send data between two unity instances on two separate computers.

I can receive the data from Unity to the OSC data monitor but not to my second instance of Unity (nothing shows up on the Unity OSC monitor)

You can see my config in the pictures. If someone has an idea to fix this I would be glad.

Thank you for your work :)

![Capture3](https://user-images.githubusercontent.com/23235691/71434264-fde36480-2726-11ea-9f65-5f33839b4acb.PNG)
![Capture](https://user-images.githubusercontent.com/23235691/71434266-fde36480-2726-11ea-91fd-e52997f69f9e.PNG)
![Capture2](https://user-images.githubusercontent.com/23235691/71434265-fde36480-2726-11ea-9216-32a8926d30f1.PNG)

**Comment by keijiro** [comment]
@BastienGermain Did you disable the Windows Firewall?

**Comment by BastienGermain** [comment]
Yes I try to disable the firewall and also wait for a few minutes but still nothing...

**Comment by NickKHarrison** [comment]
Disabling the Firewall solved this - OSC messages now receiving within Unity for me. Had spent a few hours trying to troubleshoot after having no issues yesterday with Unity receiving OSC messages. BTW I was still able to receive OSC messages in the Protokol app - but not Unity, until I disabled the Firewall.
