### ISSUE TITLE
Connection lost on OS X

### ISSUE THREAD

**Issue by thomasvanta** [keijiro/OscJack#2]
Hi!!
First of all, thanks for your work!!!

I'm trying to get it running in OS X 10.10.5
When I hit play (in game mode), I can receive values as long as I transmit continuously. If I stop to send the value for around 1s, the connection get lost.
In W8.1 is working fine, I tried to build there a OS X version to test, but no success.

I'm in 5.1.1f1 and firewall is off, just in case.

Any idea what could it be?

**Comment by keijiro** [comment]
Sorry for the delay in response. I think this issue was fixed with recent updates.
