### ISSUE TITLE
In Unity 2018, UnityEvents only have static input arguments when passing their payloads to the recipient methods

### ISSUE THREAD

**Issue by cloudcover** [keijiro/OscJack#20]
When I install this .unitypackage on Unity 2018.4.10f1, the UnityEvent that gets invoked upon receiving an OSC payload does not allow me to pass in a dynamic value, only static values. Dynamic payloads are permitted in Unity 2017.4.33f1. I would try to hack this myself, but the invocations and their payloads seem to be locked away a bit lower level than I can manage myself.

Are you also seeing this?

**Comment by cloudcover** [comment]
As far as I can tell, this issue is only reproducible in Unity 2018. The latest releases of Unity 2019 and 2017 respectively don't have this issue.

**Comment by keijiro** [comment]
That's a known issue of Unity 2018/2019/2020.

https://issuetracker.unity3d.com/issues/events-generated-by-the-player-input-component-do-not-have-callbackcontext-set-as-their-parameter-type

A fix for this issue has been landed to 2020 and 2019, but not yet for 2018.

**Comment by keijiro** [comment]
I'm closing this issue as it's not an issue of this package (but Unity's one). Please feel free to reopen if it still reproduces after the fix is applied.

**Comment by cloudcover** [comment]
Okay, my mistake. I hadn't encountered that issue before until now. Thanks for the quick response!
