### ISSUE TITLE
Build version not working

### ISSUE THREAD

**Issue by Wenzy--** [keijiro/OscJack#22]
Hi!
      I have use this addon successfully in Unity Editor. But when I export as a standalone program ,the OSC  doesn't work. I am using Unity 2019.4.2. And already close the firewall and Unity Editor on PC. I also have tried to open the app for several minutes, but still not working. Do you have any suggestions ? Thanks

**Comment by keijiro** [comment]
I'd recommend testing it on a single machine -- running a sender app and a receiver app on the same machine and checking if they work. If they work, there is something wrong with the network connection. If they don't work, there is a problem with the building process.

**Comment by Wenzy--** [comment]
Yes. I have tested on a single machine but still not working. I get some signals from the Max and send to Unity .(On editor it is always fine) So I am not sure which part goes wrong~

**Comment by Wenzy--** [comment]
Okay. I find out the issue now...It's because the default material not display correct on the note objects in HDRP DXR mode(So nothing show on the screen). Thanks for your reply !
