### ISSUE TITLE
Property Sender doesn't transmit rotation properties, running on IOS 14.2

### ISSUE THREAD

**Issue by zacksettel** [keijiro/OscJack#26]
Running on IOS (14.2) built on Unity 2020.2.5  ,  Property Sender fails to send rotation properties.  It functions normally when run on the desktop.   Property Sender functions normally when sending position properties, non both desktop and IOS.  

A custom debugging script using the Property Sender code with a hardcoded rotation value assign (e.g.  rotEulers = transform.rotation.eulerAngles) works fine.  

I suspect that the problem occurs when Property Sender tries to obtain the rotation property(ies).

**Comment by keijiro** [comment]
Could you try putting `link.xml` like this?

https://github.com/keijiro/MidiAnimationTrack/blob/master/Assets/link.xml

**Comment by zacksettel** [comment]
Hey Keijiro

Put a copy of link.xml, and the problem disappeared. (IOS 14.2).

Thanks for the quick turnaround!


cheers

Zack Settel
