### ISSUE TITLE
Unity don´t receive OSC inputs but it does in OSC Data monitor 

### ISSUE THREAD

**Issue by Tonieh** [keijiro/OscJack#28]
I while ago I used the OscJack connecting an Oculus Quest to a laptop and worked perfectly <3. Now I need to do something similar but I can´t get a connection with Unity.

I'm using this repo with Unity 2019.4.24 with the firewall deactivated, also wait several minutes to see if it could connect.
Tested with an Android.

**Comment by keijiro** [comment]
> Now I need to do something similar

Could you describe what the "something similar" is? I have no idea what you're trying to do.

**Comment by Tonieh** [comment]
> > Now I need to do something similar
> 
> Could you describe what the "something similar" is? I have no idea what you're trying to do.

Sorry for the late response.

I used the OSC jack to sent vector 3 info and some ints. Using Oculus Quest to a PC with a router.
I tried today with this plugin and works fine: https://assetstore.unity.com/packages/tools/input-management/extosc-open-sound-control-72005

**Comment by keijiro** [comment]
I'm closing this issue as assuming that you solved the problem on your side using another plugin. Please feel free to reopen it for further problems.

**Comment by PistonPL** [comment]
Same problem here.  1.0.3  Monitor does capture all messages, but sample code don't.
