### ISSUE TITLE
Getting Object reference error using any value type on receiver.

### ISSUE THREAD

**Issue by eric29** [keijiro/OscJack#29]
I have an Event Receiver component setup to receive a simple string for testing this osc plugin. But I keep getting this error, no matter which data type I use. The error line  obviously changes depending on the datatype, but it all points to the same file. I used to use this plugin on an old project in 2019.2 and it worked fine, but now I'm using 2021.1.11f1.

`NullReferenceException: Object reference not set to an instance of an object
OscJack.OscEventReceiver.Update () (at Assets/OscJack/Runtime/Unity/OscEventReceiver.cs:207)`

**Comment by keijiro** [comment]
Thanks for reporting the issue. Could you provide a minimal project that reproduces the issue?

**Comment by eric29** [comment]
I tried creating a simple project to reproduce the error, but then I wasn't getting the same error. So it was an issue in my own project. I reimported everything and got it working with no errors.

I apologize for creating an issue out of nothing, but thanks non-the-less for taking the time to try and resolve my issue!
