### ISSUE TITLE
Feature Request: Support OSC Send

### ISSUE THREAD

**Issue by polyrhythmatic** [keijiro/OscJack#3]
I really love this library. So firstly - thank you. I've looked at most of the OSC libraries for Unity and I think this one is by far the easiest to implement, and doesn't drop messages like other libraries.

I am using it for a project where I would like to be able to send OSC from Unity. Is this an easy addition to the current code base? I would prefer to continue using OscJack rather than the alternative libraries.

I'd submit a pull request but it looks a bit beyond what I am capable of, and I'm not sure how this works, or if you are interested...

**Comment by polyrhythmatic** [comment]
Hey @keijiro , I tried incorporating the Osc send from [this library](https://github.com/polyrhythmatic/unity-osc-receiver).

I'm having issues with getting it to send messages - do you know what is going on here? For some reason I can't get it to make an OscMessage object.

[Here is a link to my fork](https://github.com/polyrhythmatic/OscJack)

**Comment by polyrhythmatic** [comment]
@keijiro got the library to work but it's pretty ugly right now. I can't figure out how to incorporate your OscMessage struct with the OscMessage class I need to use. Would love to hear your thoughts - it works fine for me at the moment and for the project I need it for, but I would be willing to make a pull request if I can clean it up.

**Comment by keijiro** [comment]
The sender functionality was implemented in the latest version (v2).
