### ISSUE TITLE
Is there a way to change the IP and Port of all Senders or Receivers by code?

### ISSUE THREAD

**Issue by eric29** [keijiro/OscJack#30]
I'm trying to make it so I can change the IP and Port number of the Property Senders and Receivers with an InputField in my app, but I can't seem to find a way to do this in runtime.

(Not sure how to add the "Question" label on here)

**Comment by keijiro** [comment]
At the moment, there is no runtime property to change those attributes. I'm considering adding them in future updates.

**Comment by eric29** [comment]
Thank you.
