### ISSUE TITLE
Is there a easy way to modify or extend the OscJack?

### ISSUE THREAD

**Issue by daangijzen** [keijiro/OscJack#31]
Just a quick question, is there a easy way to modify the Osc Scripts? 
I would like to make some fields public, or at leas accessible so I can change the IP dynamically, or trough other scripts.

Do you have any tips on where to start? or what I should try?

Thanks

**Comment by keijiro** [comment]
I'd recommend learning how to program with Unity. The official tutorials may be helpful.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
