### ISSUE TITLE
Unity can't see OscJack namespace on 1.0.3 but 1.0.2 works

### ISSUE THREAD

**Issue by LSDdev** [keijiro/OscJack#32]
This might be my ignorance on Unity's inner workings. My problem is that using OscJack 1.0.2 scripting interface on my project works fine. When I upgrade the package via package manager to 1.0.3 the Unity can't seem to find the libraries and namespaces anymore and console gets flooded with 
```
The type or namespace name 'OscJack' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'OscClient' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by keijiro** [comment]
Could you provide a minimal project that can reproduce the issue?

**Comment by LSDdev** [comment]
Here is barebone project https://drive.google.com/file/d/19W2zB4999teoSoUeWsqas4gaGx3LqO9m/view?usp=sharing

It has game object with humanoid character, on that character there is something called ‘AudioControlPointController’ that enables you to select bone points and pass info from those points via osc. That AudioControlPointController links to OscJack and works with 1.0.2 but not on 1.0.3

Cheers,
jokke



From: Keijiro Takahashi ***@***.***>
Date: Tuesday, 2. November 2021 at 18.26
To: keijiro/OscJack ***@***.***>
Cc: Heikkilä Jokke ***@***.***>, Author ***@***.***>
Subject: Re: [keijiro/OscJack] Unity can't see OscJack namespace on 1.0.3 but 1.0.2 works (Issue #32)

Could you provide a minimal project that can reproduce the issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkeijiro%2FOscJack%2Fissues%2F32%23issuecomment-957918122&data=04%7C01%7Cjokke.heikkila%40uniarts.fi%7C52f8bcba1b5a47ddd9b308d99e1d948e%7C6d91fdaf2bb0431db89064c148694bac%7C0%7C0%7C637714672154132174%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BPF%2FGkomR4s4u%2B2%2Fw9Mh%2B1Toq84SxxuZiWDYIPwRcCU%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAD2FWTPTUKHXXCU3LJ4UQMLUKAGMZANCNFSM5HGYPJOQ&data=04%7C01%7Cjokke.heikkila%40uniarts.fi%7C52f8bcba1b5a47ddd9b308d99e1d948e%7C6d91fdaf2bb0431db89064c148694bac%7C0%7C0%7C637714672154142164%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JXak2tKAU7wcN7JAdFMXIKiXm8bRTH0kyl45XlmmFCw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjokke.heikkila%40uniarts.fi%7C52f8bcba1b5a47ddd9b308d99e1d948e%7C6d91fdaf2bb0431db89064c148694bac%7C0%7C0%7C637714672154142164%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=y3I5tmSDUMAQ77i%2Fxm4ne2%2BZLd6e6sQiM3omZEUTf1k%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjokke.heikkila%40uniarts.fi%7C52f8bcba1b5a47ddd9b308d99e1d948e%7C6d91fdaf2bb0431db89064c148694bac%7C0%7C0%7C637714672154152168%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LqfJ1bTomf8av3BvP8crTaASavTEmSllU9TJ6rpT2QY%3D&reserved=0>.

**Comment by keijiro** [comment]
Thanks for sharing the project.

I found there is a wrong reference from SoundActor. This issue should be fixed on their side. Please report it to them.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
