### ISSUE TITLE
Scoped registry doesn't work while trying to pull from package manager?

### ISSUE THREAD

**Issue by YichenWangs** [keijiro/OscJack#35]
Hi there,

I was trying to set up OscJack in my unity project and when I followed the registry instruction, package manager threw me this error:

`
[Package Manager Window] Cannot perform upm operation: Unable to perform online search:
  Cannot fetch authorization code. User access token is expired or invalid. You may need to sign out and sign in again. [Unknown].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
`
`
[Package Manager Window] Error while getting auth code: System.InvalidOperationException: Failed to call Unity ID to get auth code.
UnityEditor.AsyncHTTPClient:Done (UnityEditor.AsyncHTTPClient/State,int)
`

which I think it means something wrong happened from the registry end? Can please double check if it is possible? 

Thanks for this great work!
Cheers.

**Comment by keijiro** [comment]
Sometimes this issue happens to me too. For my cases, strangely, it's solved by re-syncing the clock on my computer (I'm using Linux/Windows dual booting environment, and it causes clock de-sync when switching the OSes).

I'd recommend re-syncing the clock on your computer. If you're using a VPN, I also recommend turning it on/off.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it if it still reproduces.
