### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object OscJack.OscEventReceiver.Update 

### ISSUE THREAD

**Issue by Gildas310** [keijiro/OscJack#36]
Hello Keijiro,

I receive this error:

NullReferenceException: Object reference not set to an instance of an object
OscJack.OscEventReceiver.Update () (at Library/PackageCache/jp.keijiro.osc-jack@2.0.0/Runtime/Unity/OscEventReceiver.cs:206)

NullReferenceException: Object reference not set to an instance of an object
OscJack.OscEventReceiver.Update () (at Library/PackageCache/jp.keijiro.osc-jack@2.0.0/Runtime/Unity/OscEventReceiver.cs:211)

Can you help to solve it ?

Thank you

**Comment by keijiro** [comment]
Could you provide a minimal project that reproduces the issue?

**Comment by Gildas310** [comment]
I have just changed the port number and it's working.

Sorry for the inconvenience

Thank you
