### ISSUE TITLE
Receiving issue with ofx apps

### ISSUE THREAD

**Issue by TheBricktop** [keijiro/OscJack#6]
Ive set up osc as told, but cant get any data to appear. While touchdesigner receives data with no problem so its not port/ip problem.
It might be because this osc implementation doesnt handle bundles .

**Comment by keijiro** [comment]
It does support OSC bundles because my rig depends on it. So I guess it's not an issue about bundles.

Could you provide further information about OSC messages that you're trying to receive with this plugin?

**Comment by TheBricktop** [comment]
Yeah sorry about that , it was the hidden 'advanced' settings of firewall that was blocking net traffic. Its funny because every other settings were for unity editor were allowed.
Win 10 has pretty sneaky way of blocking connetions.

**Comment by keijiro** [comment]
Thanks. I’m thinking of adding a note about firewall to the FAQ section.
